# Generated by Django 3.2 on 2022-09-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_disliketweet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liketweet',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='liketweet',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='liketweet',
            name='user',
        ),
        migrations.DeleteModel(
            name='DislikeTweet',
        ),
        migrations.DeleteModel(
            name='LikeTweet',
        ),
    ]
