# Generated by Django 3.2 on 2022-09-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_disliketweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeTweet',
        ),
    ]
