# Generated by Django 3.2 on 2022-09-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_delete_liketweet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disliketweet',
            unique_together=set(),
        ),
    ]
